src/Entity/Output.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="sorties")
 * @ORM\Entity(repositoryClass="App\Repository\OutputRepository")
 */
class Output
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Expression(
     *     "this.getQuantity() < this.getProduit().getQuantity()",
     *     message="Quantitté sortie trop élevée que le stock"
     * )
     * @Assert\GreaterThanOrEqual(message="Quantitté minimum 1", value=1)
     * @Assert\Type(
     *     type="integer",
     *     message="The value {{ value }} is not a valid {{ type }}."
     * )
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="outputs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $produit;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     * @Assert\DateTime
     */
    private $outputed_at;

    /**
     * @ORM\Column(type="text")
     */
    private $observation;

    /**
     * Output constructor.
     */
    public function __construct()
    {
        $this->outputed_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getProduit(): ?Product
    {
        return $this->produit;
    }

    public function setProduit(Product $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getOutputedAt(): ?\DateTimeInterface
    {
        return $this->outputed_at;
    }

    public function setOutputedAt(\DateTimeInterface $created_at): self
    {
        $this->outputed_at = $created_at;

        return $this;
    }

    public function getObservation(): ?string
    {
        return $this->observation;
    }

    public function setObservation(string $observation): self
    {
        $this->observation = $observation;

        return $this;
    }

}

src/Form/OutputType.php
<?php

namespace App\Form;

use App\Entity\Output;
use App\Entity\Product;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OutputType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('produit', EntityType::class, [
                'class' => Product::class,
                'placeholder' => 'Choisir le produit',
                'choice_label' => 'name',
                'query_builder' => function(EntityRepository $er){
                    return $er->createQueryBuilder('p')
                        ->orderBy('p.name', 'ASC')
                        ->where('p.isExitPermit = :isPermit')
                        ->setParameter('isPermit', 1);
                },
                'mapped' => true,
                'required' => true
            ])
            ->add('quantity')
//            ->add('outputed_at', DateTimeType::class, [
//                'empty_data' => ''
//            ])
            ->add('observation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Output::class,
            'csrf_protection' => false,
        ]);
    }
}

src/Controller/OutputController.php
<?php

namespace App\Controller;

use App\Entity\Output;
use App\Form\OutputType;
use App\Repository\OutputRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/output")
 */
class OutputController extends AbstractController
{
    /**
     * @Route("/", name="output_index", methods={"GET"})
     * @param OutputRepository $outputRepository
     * @return Response
     */
    public function index(OutputRepository $outputRepository): Response
    {
        return $this->render('output/index.html.twig', [
            'outputs' => $outputRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="output_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $output = new Output();
        $form = $this->createForm(OutputType::class, $output);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($output);
            $entityManager->flush();

            return $this->redirectToRoute('output_index');
        }

        return $this->render('output/new.html.twig', [
            'output' => $output,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="output_show", methods={"GET"})
     */
    public function show(Output $output): Response
    {
        return $this->render('output/show.html.twig', [
            'output' => $output,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="output_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Output $output): Response
    {
        $form = $this->createForm(OutputType::class, $output);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('output_index', [
                'id' => $output->getId(),
            ]);
        }

        return $this->render('output/edit.html.twig', [
            'output' => $output,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="output_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Output $output): Response
    {
        if ($this->isCsrfTokenValid('delete'.$output->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($output);
            $entityManager->flush();
        }

        return $this->redirectToRoute('output_index');
    }
}

templates/output/_delete_form.html.twig
<form method="post" action="{{ path('output_delete', {'id': output.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ output.id) }}">
    <button class="btn">Delete</button>
</form>

templates/output/_form.html.twig
<div class="container">
    {{ form_start(form) }}
        <div class="row">
            <div class="form-group col-6">
                {{ form_label(form.produit, 'Produit') }}
                {{ form_widget(form.produit) }}
            </div>
            <div class="form-group col-6">
                {{ form_label(form.quantity, 'Quantité') }}
                {{ form_widget(form.quantity) }}
            </div>
        </div>
        <div class="row">
            <div class="form-group col">
                {{ form_label(form.observation, 'Observation') }}
                {{ form_widget(form.observation) }}
            </div>
        </div>
    <button class="btn btn-primary">Ajouter</button>
    {{ form_end(form, {'render_rest': false}) }}
</div>

templates/output/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Edit Output{% endblock %}

{% block body %}
    <h1>Edit Output</h1>

    {{ include('output/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('output_index') }}">back to list</a>

    {{ include('output/_delete_form.html.twig') }}
{% endblock %}

templates/output/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Output index{% endblock %}

{% block body %}
    <h1>Output index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantity</th>
                <th>Outputed_at</th>
                <th>Observation</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for output in outputs %}
            <tr>
                <td>{{ output.id }}</td>
                <td>{{ output.quantity }}</td>
                <td>{{ output.outputedAt ? output.outputedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ output.observation }}</td>
                <td>
                    <a href="{{ path('output_show', {'id': output.id}) }}">show</a>
                    <a href="{{ path('output_edit', {'id': output.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('output_new') }}">Create new</a>
{% endblock %}

templates/output/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}New Output{% endblock %}

{% block body %}
    <h1>Create new Output</h1>
    {% for message in app.session.flashBag.get('error') %}
        <div class="alert alert-danger" role="alert" style="margin-top: 2%">
            <button type="submit" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <div>{{ message }}</div>
        </div>
    {% endfor %}
    {{ include('output/_form.html.twig') }}

    <a href="{{ path('output_index') }}">back to list</a>
{% endblock %}

templates/output/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Output{% endblock %}

{% block body %}
    <h1>Output</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ output.id }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ output.quantity }}</td>
            </tr>
            <tr>
                <th>Outputed_at</th>
                <td>{{ output.outputedAt ? output.outputedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Observation</th>
                <td>{{ output.observation }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('output_index') }}">back to list</a>

    <a href="{{ path('output_edit', {'id': output.id}) }}">edit</a>

    {{ include('output/_delete_form.html.twig') }}
{% endblock %}